name: stamp_rally
description: "Stamp Rally"
publish_to: 'none'
version: 1.0.3+10

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  hooks_riverpod: 2.4.9
  riverpod_annotation: 2.3.3
  flutter_hooks: 0.20.4
  shared_preferences: 2.2.2
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  logger: 2.0.2+1
  go_router: 13.0.1
  extended_image: 8.2.0
  intl: ^0.19.0
  slang: 3.29.0
  slang_flutter: 3.29.0
  gap: 3.0.1
  theme_tailor_annotation: 2.0.2
  http: 1.2.0
  csv: 5.1.1
  geolocator: 10.1.0
  mobile_scanner: 3.5.5
  url_launcher: ^6.3.0
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  supabase_flutter: ^2.6.0
  url_launcher_ios: ^6.3.1
  frontend_server_client: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: 2.3.9
  freezed: 2.4.6
  json_serializable: 6.7.1
  flutter_gen_runner: 5.4.0
  flutter_lints: 3.0.1
  riverpod_lint: 2.3.7
  build_runner: ^2.4.13
  go_router_builder: 2.4.1
  flutter_launcher_icons: 0.13.1
  theme_tailor: 2.0.2

flutter_gen:
  output: lib/assets/

flutter:
  uses-material-design: true

  assets:
    - assets/png/